### ISSUE TITLE
Url slug is not set in models 

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-js#10]
Loading content using typescript SDK raise a warning that URL slug is not implemented:
* You have to implement 'urlSlugResolver' in your Model class or your query in order to get url of this item
field-types.js:196

i.e. Home page raise this warning 9 times.

Consequences on the content, that uses some links in rich text does not resolve them properly.
Example:
Link in article detail (http://localhost:3000/#/articles/coffee-processing-techniques)
contains link to  Brazil Natural Barra Grande (content type Coffee) is not resolve
Expected:
http://localhost:3000/#/store/coffees/brazil-natural-barra-grande
But is
http://localhost:3000

![image](https://user-images.githubusercontent.com/9218736/29966781-bce46fc2-8f13-11e7-9156-7e63e4c7dc46.png)

**Comment by Enngage** [comment]
I'll try looking at this
