### ISSUE TITLE
Restore Preview API functionality

### ISSUE THREAD

**Issue by AaronCKentico** [Kentico/cloud-sample-app-js#12]
As part of the update to the TypeScript SDK, the Preview API was taken out of the default behavior. It should be restored so that the instructions in README.md enable users to easily enable previews from the sample app.

**Comment by Simply007** [comment]
Created branch with the client fix
* https://github.com/Kentico/cloud-sample-app-js/tree/preview_functionality

**Comment by Simply007** [comment]
Pull request:
https://github.com/Kentico/cloud-sample-app-js/pull/13

**Comment by petrsvihlik** [comment]
thanks @Simply007 !
