### ISSUE TITLE
Problem with preview API (CORS, method OPTIONS)

### ISSUE THREAD

**Issue by KenticoMarianV** [Kentico/cloud-sample-app-js#6]
Hi!
I have downloaded project and done everything according to instructions. It works fine when previewApiKey is not provided. When I have set api key I have ended with errors:

![2017-03-28 20_12_37-program manager](https://cloud.githubusercontent.com/assets/24543224/24420387/08efa522-13f3-11e7-9268-0e6b07d7ae8f.png)
![2017-03-28 20_12_59-developer tools - http___localhost_3001_](https://cloud.githubusercontent.com/assets/24543224/24420388/090d2fc0-13f3-11e7-9a5b-450cf2c6775f.png)

**Comment by alesk-kentico** [comment]
Hi Marián, there was a problem with CORS configuration that has been fixed. Thank you for your feedback!
