### ISSUE TITLE
Inline content modules are not loaded properly

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-js#8]
Application does not count with the inline content module within the rich text element. 

Example on coffee-beverages-explained article:
![image](https://user-images.githubusercontent.com/9218736/29705016-8310ee02-897c-11e7-9fb8-7dc7987e4248.png)

This change was made @jancerman (Andrew Dixon) on Jun 27, 2017 · 3:12 pm according to revision history.

**Comment by Simply007** [comment]
Pull requests:
https://github.com/Kentico/cloud-sample-app-js/pull/15

**Comment by petrsvihlik** [comment]
resolved! thx @Simply007
